"""Minimal llama.cpp client (OpenAI-compatible) for newsletter generation.

Drop-in replacement for `pipeline.ollama_client.chat` against a
`llama-server` instance speaking the OpenAI Chat Completions API on
http://127.0.0.1:8090/v1/chat/completions.

Only the `chat()` signature used by the newsletter generator is provided.
"""

import logging
import os
import threading
import time
from pathlib import Path
from typing import Callable, TypeVar

import httpx
from pydantic import BaseModel

from pipeline.config import MAX_RETRIES
from pipeline.content_guard import GarbledOutputError

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)


class ModelMismatchError(RuntimeError):
    """llama-server on :8090 serves a different model than the stage expects.

    llama-server ignores the `model` field of a request and answers with
    whatever GGUF it has loaded. If another job swapped the server mid-stage
    (2026-09-05: the Saturday ingesters replaced the cycle's Gemma with the
    embedding model), every further request would be generated by the wrong
    model — 200 OK, garbage content. Raised instead of retried: the stage
    must abort and leave its entries unprocessed (#98)."""

LLAMACPP_HOST = os.getenv("LLAMACPP_HOST", "http://127.0.0.1:8090")
TIMEOUT = float(os.getenv("LLAMACPP_TIMEOUT", "600"))
# Headroom for GeneratedContent (title+summary+150-250w body+attribution).
# Grammar-constrained decoding force-closes JSON when the budget is hit, which
# yields valid-but-truncated output — so give enough room to finish naturally.
MAX_TOKENS = int(os.getenv("LLAMACPP_MAX_TOKENS", "1024"))
# Ceiling for the truncation retry below: an attempt that hit the length
# limit gets a bigger budget, but never an unbounded one — a runaway
# enumeration must fail loudly rather than generate for minutes.
TRUNCATION_MAX_TOKENS = int(os.getenv("LLAMACPP_TRUNCATION_MAX_TOKENS", "8192"))


# Identity gate (#98). One GET /v1/models per TTL window per expected model —
# a batch of concurrent requests shares a single check; a RETRY always
# re-checks (the retry path is exactly where a swapped server shows up first:
# the old one died with "connection refused", the new one answers with the
# wrong model).
MODEL_CHECK_TTL = float(os.getenv("LLAMACPP_MODEL_CHECK_TTL", "30"))
_model_check_last: dict[str, float] = {}
_model_check_lock = threading.Lock()


def served_model_id() -> str | None:
    """Model id llama-server currently reports on GET /v1/models, or None if
    the server is unreachable / answers garbage. Same extraction as
    pipeline.gpu_handover._served_model."""
    try:
        r = httpx.get(f"{LLAMACPP_HOST}/v1/models", timeout=5)
        r.raise_for_status()
        data = r.json()
        entry = (data.get("data") or data.get("models") or [{}])[0]
        return entry.get("id") or entry.get("name") or None
    except Exception:  # noqa: BLE001 — unreachable is a verdict of its own
        return None


def model_matches(expected: str, served: str | None) -> bool:
    """True if the served id names the expected model. Expected is a GGUF
    filename (Stages 2-6) or a served alias (judge: "Qwen3.8-27B"); served ids
    are the GGUF basename or path, so basename containment is the contract
    (mirrors gpu_handover._model_ready)."""
    if not served:
        return False
    exp = Path(expected).name
    return exp == served or exp in served or Path(served).name == exp


def assert_served_model(expected: str, stage: str = "", force: bool = False) -> None:
    """Abort with ModelMismatchError if :8090 serves the wrong model.

    Cached for MODEL_CHECK_TTL seconds per expected model unless `force`.
    An UNREACHABLE server is not a mismatch: the request itself will fail and
    go through the normal retry path, which re-checks with force=True."""
    now = time.monotonic()
    if not force:
        with _model_check_lock:
            last = _model_check_last.get(expected)
        if last is not None and now - last < MODEL_CHECK_TTL:
            return
    served = served_model_id()
    label = stage or Path(expected).name
    if served is None:
        logger.warning("model identity check (%s): llama-server at %s unreachable — "
                       "the request itself will decide", label, LLAMACPP_HOST)
        return
    if not model_matches(expected, served):
        raise ModelMismatchError(
            f"{label}: llama-server at {LLAMACPP_HOST} serves {served!r}, expected "
            f"{Path(expected).name!r} — another job swapped the model under this stage "
            f"(#98); aborting instead of generating against the wrong model")
    with _model_check_lock:
        _model_check_last[expected] = now


def _add_sampling(payload: dict, top_p: float | None = None,
                  top_k: int | None = None, min_p: float | None = None,
                  presence_penalty: float | None = None) -> dict:
    """Nur gesetzte Sampling-Felder in die Payload — nie einen Default."""
    for key, val in (("top_p", top_p), ("top_k", top_k), ("min_p", min_p),
                     ("presence_penalty", presence_penalty)):
        if val is not None:
            payload[key] = val
    return payload


def chat(model: str, prompt: str, system: str | None = None,
         temperature: float = 0.0, seed: int | None = None,
         max_tokens: int | None = None, top_p: float | None = None,
         top_k: int | None = None, min_p: float | None = None,
         presence_penalty: float | None = None) -> str:
    """Send a chat request to llama-server and return the response text.

    `seed` / `max_tokens` are optional and only sent when given (Research
    Pulse, #73: fixed seed for reproducible weekly paragraphs); the
    newsletter's calls are byte-identical to before.

    `top_p` / `top_k` / `min_p` / `presence_penalty` likewise: sie existieren,
    damit ein Aufrufer so sampeln kann, wie es die Modellkarte vorschreibt,
    statt nur ueber die Temperatur (Dossier-DR-Modus 2026-09-07 — Qwen3.8
    nicht-denkend ist mit temp 0.7, top_p 0.80, top_k 20, presence_penalty 1.5
    spezifiziert). Nicht gesetzt heisst: das Feld geht gar nicht mit, also
    bleibt jeder bestehende Aufruf byte-identisch."""
    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})

    payload: dict = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "stream": False,
    }
    if seed is not None:
        payload["seed"] = seed
    if max_tokens is not None:
        payload["max_tokens"] = max_tokens
    _add_sampling(payload, top_p=top_p, top_k=top_k, min_p=min_p,
                  presence_penalty=presence_penalty)

    url = f"{LLAMACPP_HOST}/v1/chat/completions"
    logger.debug("llama.cpp chat → %s (model=%s, T=%.2f)", url, model, temperature)
    with httpx.Client(timeout=TIMEOUT) as client:
        r = client.post(url, json=payload)
        r.raise_for_status()
        data = r.json()
    try:
        return data["choices"][0]["message"]["content"] or ""
    except (KeyError, IndexError) as e:
        logger.error("llama.cpp response missing content: %s — body=%s", e, data)
        return ""


def _strip_fences(raw: str) -> str:
    """Remove markdown code fences some models wrap JSON in."""
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        first_newline = cleaned.index("\n")
        cleaned = cleaned[first_newline + 1:]
        if cleaned.rstrip().endswith("```"):
            cleaned = cleaned.rstrip()[:-3].rstrip()
    return cleaned


def _json_schema(schema, require_all_fields: bool):
    """The schema sent to llama-server.

    Pydantic marks only fields WITHOUT a default as required, and every field of
    ExtractionResult has one — so `required` was absent entirely and the grammar
    happily let the model omit brand_name, key_claims and quotes. It did:
    measured 0/14 brands and 0 claims across 14 articles. Listing every property
    as required forces a value for each (an empty list is still a legal value,
    so nothing is fabricated by construction).

    Opt-in per call: relevance and classification are unaffected, since forcing
    fields there would change decisions rather than fill in evidence.
    """
    js = schema.model_json_schema()
    if require_all_fields and "properties" in js:
        js["required"] = list(js["properties"].keys())
    return js


def chat_structured(model: str, prompt: str, schema: type[T],
                    system: str | None = None, temperature: float = 0.0,
                    fallback_model: str | None = None,
                    validate: Callable[[T], bool] | None = None,
                    max_validate_retries: int | None = None,
                    require_all_fields: bool = False,
                    max_tokens: int | None = None,
                    verify_model: bool = False,
                    hard_validate: Callable[[T], list[str]] | None = None,
                    cache_prompt: bool | None = None,
                    top_p: float | None = None,
                    top_k: int | None = None,
                    min_p: float | None = None) -> T | None:
    """Structured output against llama-server (OpenAI json_schema response_format).

    Mirrors pipeline.ollama_client.chat_structured: retry loop, markdown fence
    stripping, Pydantic validation. Thinking is disabled to avoid CoT bloat in
    the JSON payload (Qwen3 equivalent of Ollama's think=False).

    `validate`: optional content guard. If it returns False for a parsed result
    the call is retried. The last result is returned anyway once the retry budget
    is exhausted — a flagged body beats None (which loses the entry).
    `max_validate_retries`: cap on *content-guard* retries (separate from HTTP/JSON
    error retries, which keep the full MAX_RETRIES budget). Defaults to MAX_RETRIES-1.
    Set low (e.g. 1) for soft guards like the cliché check: one quick re-roll, then
    accept — avoids burning 3× GPU on output the model keeps producing anyway.
    Content-guard retries skip the exponential backoff (the server is healthy).
    `max_tokens`: initial output budget for THIS call (default: module MAX_TOKENS).
    Callers with predictably long JSON (e.g. an evidence audit) start high instead
    of burning two truncation retries per call; the doubling-on-truncation ladder
    then grows from this base, still capped at TRUNCATION_MAX_TOKENS.
    `verify_model`: identity gate (#98) — before the first attempt (TTL-cached)
    and before EVERY retry, GET /v1/models must name `model`; otherwise
    ModelMismatchError propagates (never retried, never swallowed into None) so
    the calling stage aborts and its entries stay unprocessed.
    `hard_validate`: HARD content guard (#11, 2026-09-05) — returns the reasons
    a parsed result is unusable garbage (pipeline.content_guard.garbage_reasons).
    Unlike `validate`, a rejected result is NEVER returned: the call is retried
    with a fresh request that disables llama-server's prompt-cache reuse
    (`cache_prompt: false` — the 22 garbage bodies of 2026-09-05 came out of one
    slot in a row while the same prompts had been fine before and were fine
    again afterwards, so a corrupted reused prefix is the leading suspect), and
    when the budget is spent GarbledOutputError propagates instead of a body
    that would otherwise be stored as a draft with confidence 0.93.
    `cache_prompt`: None = llama-server default (prefix reuse on); False sends
    `cache_prompt: false` from the FIRST request — the A/B arm of
    scripts/repro_stage6_garbage.py."""
    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})

    payload = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "stream": False,
        "max_tokens": max_tokens or MAX_TOKENS,
        "response_format": {
            "type": "json_schema",
            "json_schema": {
                "name": schema.__name__,
                "schema": _json_schema(schema, require_all_fields),
                "strict": True,
            },
        },
        "chat_template_kwargs": {"enable_thinking": False},
    }
    if cache_prompt is not None:
        payload["cache_prompt"] = cache_prompt
    # Kein presence_penalty auf grammatik-gebundener Ausgabe: die Strafe traefe
    # die Schluesselnamen des Schemas, die sich wiederholen MUESSEN.
    _add_sampling(payload, top_p=top_p, top_k=top_k, min_p=min_p)

    url = f"{LLAMACPP_HOST}/v1/chat/completions"
    vcap = max_validate_retries if max_validate_retries is not None else MAX_RETRIES - 1
    vfails = 0
    for attempt in range(MAX_RETRIES):
        if verify_model:
            assert_served_model(model, stage=schema.__name__, force=attempt > 0)
        try:
            with httpx.Client(timeout=TIMEOUT) as client:
                r = client.post(url, json=payload)
                r.raise_for_status()
                data = r.json()
            choice = data["choices"][0]
            raw = choice["message"]["content"] or ""
            if not raw.strip():
                raise ValueError("Empty response from model")
            if choice.get("finish_reason") == "length":
                # Give the NEXT attempt more room instead of replaying the same
                # request. At temperature 0 an identical payload should yield an
                # identical truncation — that retries succeeded at all was down
                # to llama.cpp not being bit-deterministic (batch composition
                # shifts float reduction order). Hoping for numerical noise is
                # not error handling. Doubling is capped so one pathological
                # input cannot drag the whole run into huge generations.
                grown = min((max_tokens or MAX_TOKENS) * (2 ** (attempt + 1)),
                            TRUNCATION_MAX_TOKENS)
                if grown > payload["max_tokens"]:
                    logger.warning("Output truncated (finish_reason=length at "
                                   "max_tokens=%d) — retrying with %d",
                                   payload["max_tokens"], grown)
                    payload["max_tokens"] = grown
                else:
                    logger.warning("Output truncated at the %d-token ceiling — "
                                   "the prompt or schema is the problem, not the limit",
                                   payload["max_tokens"])
            result = schema.model_validate_json(_strip_fences(raw))
            if hard_validate is not None:
                garbage = hard_validate(result)
                if garbage:
                    if attempt < MAX_RETRIES - 1:
                        logger.warning("HARD guard rejected output for %s (%s) — fresh "
                                       "request without prompt cache (attempt %d/%d)",
                                       model, ", ".join(garbage[:4]), attempt + 1, MAX_RETRIES)
                        payload["cache_prompt"] = False
                        continue
                    raise GarbledOutputError(
                        f"{schema.__name__}: all {MAX_RETRIES} attempts on {model} produced "
                        f"garbage ({', '.join(garbage[:4])}) — nothing stored")
            if validate is not None and not validate(result):
                vfails += 1
                if vfails <= vcap and attempt < MAX_RETRIES - 1:
                    logger.warning("Content guard rejected output for %s "
                                   "(cliché retry %d/%d) — re-rolling", model, vfails, vcap)
                    continue  # no backoff: server is healthy, just re-roll
                return result  # validate budget spent → accept the last result
            return result
        except GarbledOutputError:
            raise
        except Exception as e:
            logger.warning("Attempt %d/%d failed for %s: %s",
                           attempt + 1, MAX_RETRIES, model, e)
            if attempt < MAX_RETRIES - 1:
                time.sleep(2 ** attempt)
                continue
            logger.error("All attempts exhausted for %s", model)
            return None


class EmbeddingBackendError(RuntimeError):
    """The embedding SERVER failed (connection refused, timeout, 5xx/429) —
    not the text. Callers must not mark the entry as filtered; it stays
    unprocessed for a retry (#98 d: 2,416 entries were written off as
    'embedding_error' on 2026-09-05 while the server was simply down)."""


def is_backend_failure(exc: BaseException) -> bool:
    """Transport-level or server-side failure, as opposed to a content problem
    (4xx for an over-long/empty input, malformed JSON) that a retry will not fix."""
    if isinstance(exc, (httpx.TransportError, ConnectionError)):
        return True
    if isinstance(exc, httpx.HTTPStatusError):
        code = exc.response.status_code
        return code >= 500 or code == 429
    return False


def generate_embedding(text: str, model: str | None = None,
                       strict: bool = False) -> list[float] | None:
    """Generate an embedding vector via llama-server's OpenAI-compatible endpoint.

    Drop-in replacement for `pipeline.ollama_client.generate_embedding`. Hits
    POST {LLAMACPP_HOST}/v1/embeddings. `model` is included in the payload but
    llama-server ignores it (the loaded model is whatever start-active.sh
    brought up); callers can pass it for logging clarity.

    `strict=True` (signal_batch): a backend failure raises EmbeddingBackendError
    instead of returning None, so the caller can tell "server down" from "this
    text cannot be embedded" — only the latter is a verdict on the entry.
    """
    payload: dict = {"input": text}
    if model is not None:
        payload["model"] = model
    url = f"{LLAMACPP_HOST}/v1/embeddings"
    try:
        with httpx.Client(timeout=TIMEOUT) as client:
            r = client.post(url, json=payload)
            r.raise_for_status()
            data = r.json()
        return data["data"][0]["embedding"]
    except Exception as e:
        if strict and is_backend_failure(e):
            raise EmbeddingBackendError(f"embedding backend failure: {e!r}") from e
        logger.error("llama.cpp embedding failed: %s", e)
        return None
