#!/usr/bin/env python3
"""Dry-run: compare Stage-5 content generation 14B (stored) vs 35B (llama.cpp).

The existing published trends were generated by qwen3:14b during their original
pipeline run — their stored body_en IS the 14B baseline. This script reconstructs
the Stage-5 inputs from stored fields and re-runs ONLY the content-generation step
against the currently loaded llama.cpp model (e.g. Qwen3.6-35B-A3B on :8090),
then prints a side-by-side diff. Nothing is written back to the DB.

CAVEAT: ExtractionResult.key_claims and product_name are not persisted, so the
35B receives slightly LESS context than the original 14B run had — if 35B still
reads better, that's a conservative (handicapped) signal.

Usage:
  STAGE5_MODEL=Qwen3.6-35B-A3B-UD-Q4_K_M.gguf \
    python -m scripts.dryrun_stage5_llamacpp [N] [--vertical FOOD]
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from pipeline.db import get_connection
from pipeline.llamacpp_client import chat_structured
from pipeline.llm_processor import CONTENT_EN_SYSTEM
from pipeline.models import ClassificationResult, ExtractionResult, GeneratedContent


def _jload(raw, default):
    try:
        v = json.loads(raw) if raw else default
        return v if v else default
    except (json.JSONDecodeError, TypeError):
        return default


def build_context(row) -> str:
    """Rebuild the Stage-5 prompt context from stored trend fields."""
    brands = _jload(row["brands"], [])
    tags = _jload(row["tags"], [])
    verticals = _jload(row["verticals"], [])
    pestel = _jload(row["pestel"], [])
    # tags used as a proxy for key_claims (real key_claims are not persisted)
    return f"""Original Title: {row['raw_title'] or row['title_en']}
Original Excerpt: {(row['excerpt'] or '')[:1000]}
Brand: {brands[0] if brands else 'Unknown'}
Product: Unknown
Key Claims: {', '.join(tags[:5]) if tags else 'N/A'}
Verticals: {', '.join(verticals)}
PESTEL: {', '.join(pestel)}
Signal Type: {row['trend_signal_type']}
Mega Trend: {row['mega_trend'] or 'N/A'}
Source: {row['source_name']} ({row['source_url']})"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("n", nargs="?", type=int, default=12, help="sample size")
    ap.add_argument("--vertical", default=None, help="filter primary_vertical")
    args = ap.parse_args()

    model = os.getenv("STAGE5_MODEL", "Qwen3.6-35B-A3B-UD-Q4_K_M.gguf")

    sql = (
        "SELECT t.id, t.title_en, t.summary_en, t.body_en, t.brands, t.tags, "
        "t.verticals, t.pestel, t.trend_signal_type, t.mega_trend, "
        "t.source_name, t.source_url, t.primary_vertical, "
        "re.title AS raw_title, re.excerpt "
        "FROM trends t LEFT JOIN raw_entries re ON re.id = t.raw_entry_id "
        "WHERE t.status='published' AND t.body_en IS NOT NULL AND re.excerpt IS NOT NULL "
    )
    params = []
    if args.vertical:
        sql += "AND t.primary_vertical=? "
        params.append(args.vertical.upper())
    sql += "ORDER BY t.created_at DESC LIMIT ?"
    params.append(args.n)

    with get_connection() as conn:
        conn.row_factory = __import__("sqlite3").Row
        rows = conn.execute(sql, params).fetchall()

    print(f"Model under test : {model}")
    print(f"Sample           : {len(rows)} trends"
          + (f" (vertical={args.vertical.upper()})" if args.vertical else ""))
    print("=" * 84)

    ok = 0
    t_total = 0.0
    for i, row in enumerate(rows, 1):
        ctx = build_context(row)
        prompt = f"Write a trend article in English based on this information.\n\n{ctx}\n\n"
        t0 = time.time()
        out = chat_structured(
            model=model, prompt=prompt, schema=GeneratedContent,
            system=CONTENT_EN_SYSTEM, temperature=0.7,
            validate=lambda c: len(c.body.split()) >= 100,
        )
        dt = time.time() - t0
        t_total += dt

        print(f"\n### [{i}/{len(rows)}] #{row['id']} [{row['primary_vertical']}] "
              f"({dt:.1f}s)")
        print(f"src: {row['raw_title']}")
        if out is None:
            print("  !! 35B returned None (schema-invalid after retries)")
            continue
        ok += 1
        b14 = (row["body_en"] or "").strip()
        b35 = (out.body or "").strip()
        print(f"\n  -- 14B stored title : {row['title_en']}")
        print(f"  -- 35B new   title : {out.title}")
        print(f"\n  -- 14B body ({len(b14.split())}w) --\n    {b14}")
        print(f"\n  -- 35B body ({len(b35.split())}w) --\n    {b35}")
        print("-" * 84)

    n = len(rows)
    print(f"\n{'='*84}\nSummary: {ok}/{n} schema-valid, "
          f"avg {t_total/max(n,1):.1f}s/call, {t_total:.0f}s total")


if __name__ == "__main__":
    main()
