#!/usr/bin/env python3
"""Generate frontend/src/lib/first-names.ts from pipeline/first_names.py (#11).

The review UI ports the person-name grounding check to TypeScript so it can
highlight the offending names live. Both sides must trigger on the same given
names, so the TS list is GENERATED from the Python one — never edited by hand.
tests/test_first_names_sync.py fails when the two drift.

    python scripts/gen_first_names_ts.py          # rewrite the .ts file
    python scripts/gen_first_names_ts.py --check  # exit 1 if it is stale
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from pipeline.first_names import FIRST_NAMES  # noqa: E402

TS_PATH = Path(__file__).parent.parent / "frontend" / "src" / "lib" / "first-names.ts"


def render() -> str:
    names = sorted(FIRST_NAMES)
    lines = ["// GENERATED by scripts/gen_first_names_ts.py from pipeline/first_names.py — do not edit.",
             f"// {len(names)} given names, lowercase. See the Python module for the exclusion policy.",
             "export const FIRST_NAMES: ReadonlySet<string> = new Set<string>(["]
    row: list[str] = []
    for n in names:
        row.append(f'"{n}"')
        if len(row) == 10:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    lines.append("]);")
    return "\n".join(lines) + "\n"


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        current = TS_PATH.read_text() if TS_PATH.exists() else ""
        if current != content:
            print(f"{TS_PATH} is stale — run scripts/gen_first_names_ts.py")
            return 1
        print("first-names.ts up to date")
        return 0
    TS_PATH.write_text(content)
    print(f"wrote {TS_PATH} ({len(FIRST_NAMES)} names)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
