/**
 * AI disclosure for the briefing AND for the feed articles (owner mandate
 * 2026-09-06, issue #99 — EU AI Act Art. 50 (4): AI-generated text on matters
 * of public interest must be labelled where it is published WITHOUT human
 * editorial control; the EU icons offered alongside the rule are optional and
 * we do not use them).
 *
 * The two products differ in exactly that point, which is why they get two
 * sentences and not one:
 *
 *   briefing  (/trends/newsletter, the mail)  — since 2026-09-06 an edition
 *             may only leave the release desk after a person has read and
 *             approved it. `AI_DISCLOSURE_EN` therefore ends on the human
 *             release; the mail carries the same sentence, so it is mirrored
 *             in Python.
 *   article   (/trends/<slug>)                — nobody reads these before they
 *             appear; they pass automatic gates only (grounding against the
 *             source, garbage/truncation, dedup). `ARTICLE_DISCLOSURE_EN`
 *             therefore says the opposite about the human, and there is no
 *             Python mirror: this path is rendered entirely by the frontend.
 *
 * Whichever sentence is shown, it stays a plain statement of fact — no
 * marketing, no method claim, nothing that would stop being true if a gate
 * were changed without changing the wording.
 *
 * What lives here:
 *
 *  1. `AI_DISCLOSURE_EN` — the one sentence that travels with every copy of an
 *     edition: the mail footer, the website edition and the release view. It
 *     is a MIRROR of `AI_DISCLOSURE_EN` in pipeline/newsletter_generator.py
 *     (the mail is rendered in Python); tests/test_newsletter_ai_disclosure.py
 *     fails if the two drift apart. Worded so it still holds if the legal
 *     review of #99 (EU AI Act Art. 50) asks for an explicit label — it names
 *     what is machine-made, that checking is automatic, and that a person
 *     released it. No marketing, no method claim.
 *
 *  2. `EDITION_BLOCKS` — per-section provenance, shown as a badge next to each
 *     block in the release view so the owner sees at a glance which part of
 *     the issue a machine wrote. Three honest kinds, kept apart on purpose:
 *       generated  a language model wrote this text
 *       computed   arithmetic over the corpus, no language model involved
 *       curated    a selection of existing articles (which are themselves
 *                  model-written from their source — said, not glossed over)
 *
 *  3. `ARTICLE_DISCLOSURE_*` — the feed-article label: the full sentence, the
 *     short text that carries it in the page's first screenful, and the
 *     `<meta name="generator">` value. No Python mirror (see above).
 */

export const AI_DISCLOSURE_EN =
  "Sections of this briefing are generated from our corpus by a local " +
  "language model and checked automatically; the selection and this edition " +
  "were reviewed and released by a person.";

/**
 * The feed article's disclosure — the express label under Art. 50 (4) for
 * /trends/<slug>. Every clause is a fact about the pipeline that produced the
 * page, and each one would have to be re-checked before it is reworded:
 *
 *   "generated ... by a local language model"  Stage 6 writes title/summary/
 *       body on our own hardware (llama.cpp on the workstation GPU).
 *   "from the single source linked below"      one raw_entry, one source_url —
 *       the article is never a synthesis of several sources, and that source
 *       is linked in full further down the same page.
 *   "checked automatically against that source" pipeline/grounding.py (concrete
 *       tokens must occur in the source), content_guard.garbage_reasons and the
 *       pgvector dedup — machine gates, all of them.
 *   "without a person reading it beforehand"   auto-publish above the
 *       confidence threshold, plus the draft judge, which is itself a model.
 *       If a human read ever becomes part of this path, this clause is false
 *       and must go — that is the point of spelling it out.
 */
export const ARTICLE_DISCLOSURE_EN =
  "This article was generated by a local language model from the single " +
  "source linked below, checked automatically against that source, and " +
  "published without a person reading it beforehand.";

/** Short text of the label itself — must be legible without expanding it. */
export const ARTICLE_DISCLOSURE_LABEL = "AI-generated";

/** The qualifier next to the label; the part a reader is least likely to assume. */
export const ARTICLE_DISCLOSURE_QUALIFIER = "not reviewed by a person";

/** Accessible name of the disclosure region (it is a note, not a heading). */
export const ARTICLE_DISCLOSURE_ARIA = "AI content disclosure";

/**
 * `<meta name="generator">` on article pages.
 *
 * There is no agreed machine-readable marker for AI-generated text: `generator`
 * is a long-standing HTML convention for "which software produced this
 * document" (WordPress et al. use it) and is the closest honest fit, so it
 * names the pipeline and what it is. Nothing consumes it as a legal signal —
 * the binding label is the visible one; see JsonLd.tsx for the schema.org half.
 */
export const ARTICLE_GENERATOR_META =
  "Catandary Trends pipeline (local large language model; AI-generated article, no human review before publication)";

export type AiProvenance = "generated" | "computed" | "curated";

export interface EditionBlock {
  /** Matches the section keys of an edition record. */
  key: "editorial" | "deep_dive" | "vertical_summaries" | "trend_refs" | "mega_trend_radar";
  label: string;
  provenance: AiProvenance;
  /** How this block came about — one sentence, no hedging. */
  detail: string;
}

export const PROVENANCE_BADGE: Record<AiProvenance, string> = {
  generated: "AI-generated",
  computed: "Computed",
  curated: "Curated",
};

export const EDITION_BLOCKS: EditionBlock[] = [
  {
    key: "editorial",
    label: "Weekly overview",
    provenance: "generated",
    detail:
      "Written by the local language model from this week's signal counts and the cited articles.",
  },
  {
    key: "deep_dive",
    label: "Deep dive",
    provenance: "generated",
    detail:
      "Researched and condensed by local language models, then checked against its own citations before it may appear.",
  },
  {
    key: "vertical_summaries",
    label: "Vertical signals",
    provenance: "generated",
    detail: "One summary per vertical, written by the local language model from that vertical's signals.",
  },
  {
    key: "trend_refs",
    label: "Cited signals",
    provenance: "curated",
    detail:
      "Selected from published articles by signal score; each linked article is itself model-written from its source and links to that source.",
  },
  {
    key: "mega_trend_radar",
    label: "Signal themes radar",
    provenance: "computed",
    detail: "Signal counts per theme, aggregated in SQL. No language model involved.",
  },
];

/** The block record for one section, or undefined for an unknown key. */
export function editionBlock(key: EditionBlock["key"]): EditionBlock | undefined {
  return EDITION_BLOCKS.find((b) => b.key === key);
}
