// AUTO-GENERATED by frontend/scripts/generate-mega-trends.mjs
// Source of truth: mega_trends.yaml at the repo root. Do not edit by hand.
import type { MegaTrendInfo } from "./types";

export const MEGA_TRENDS: MegaTrendInfo[] = [
  {
    "key": "artificial_intelligence_and_automation",
    "name_en": "Artificial Intelligence & Automation",
    "description_en": "AI/ML integration across industries — from generative AI and design tools to industrial robotics, autonomous systems, and AI-driven decision making.",
    "icon": "🤖",
    "verticals": [
      "TECH",
      "BIZ",
      "HEALTH",
      "FOOD",
      "DESIGN",
      "LIFESTYLE"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.48,
      "tiers": 4,
      "lead_months": 125,
      "lead_tier": "science",
      "dom_vertical": "TECH",
      "dom_share": 0.73
    }
  },
  {
    "key": "personalized_health_and_longevity",
    "name_en": "Personalized Health & Longevity",
    "description_en": "Precision medicine, digital therapeutics, individualized nutrition, longevity science, biomarker-driven health optimization.",
    "icon": "🧬",
    "verticals": [
      "HEALTH",
      "TECH",
      "FOOD",
      "FASHION"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.42,
      "tiers": 4,
      "lead_months": 141,
      "lead_tier": "science",
      "dom_vertical": "HEALTH",
      "dom_share": 0.65
    }
  },
  {
    "key": "clean_energy_transition",
    "name_en": "Clean Energy Transition",
    "description_en": "Decarbonization of energy, industry and transport — renewables, green hydrogen, energy storage, grid modernization, carbon capture.",
    "icon": "⚡",
    "verticals": [
      "ECO",
      "TECH",
      "BIZ",
      "LIFESTYLE"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.5,
      "tiers": 4,
      "lead_months": 48,
      "lead_tier": "science",
      "dom_vertical": "ECO",
      "dom_share": 0.56
    }
  },
  {
    "key": "electric_and_autonomous_mobility",
    "name_en": "Electric & Autonomous Mobility",
    "description_en": "Electric vehicles, autonomous driving, shared mobility platforms, urban micro-mobility, charging infrastructure, mobility-as-a-service.",
    "icon": "🚗",
    "verticals": [
      "TECH",
      "ECO",
      "DESIGN",
      "BIZ"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.62,
      "tiers": 4,
      "lead_months": 17,
      "lead_tier": "science",
      "dom_vertical": "TECH",
      "dom_share": 0.52
    }
  },
  {
    "key": "financial_innovation_and_inclusion",
    "name_en": "Financial Innovation & Inclusion",
    "description_en": "Fintech disruption, embedded finance, digital banking, decentralized finance, financial literacy, unbanked population access.",
    "icon": "💳",
    "verticals": [
      "BIZ",
      "TECH",
      "LIFESTYLE"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.53,
      "tiers": 4,
      "lead_months": 179,
      "lead_tier": "science",
      "dom_vertical": "BIZ",
      "dom_share": 0.69
    }
  },
  {
    "key": "new_luxury_and_premiumization",
    "name_en": "New Luxury & Premiumization",
    "description_en": "Luxury democratization, quiet luxury, experiential premium, artisanal positioning, luxury-mass collaborations, heritage brand renewal.",
    "icon": "💎",
    "verticals": [
      "LIFESTYLE",
      "FASHION",
      "DESIGN",
      "FOOD",
      "BIZ"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.66,
      "tiers": 3,
      "lead_months": 221,
      "lead_tier": "science",
      "dom_vertical": "FASHION",
      "dom_share": 0.51
    }
  },
  {
    "key": "regenerative_design_and_net_positive",
    "name_en": "Regenerative Design & Net Positive",
    "description_en": "Beyond sustainability — designs and systems that actively restore ecosystems, regenerative agriculture, net-positive buildings, restorative practices.",
    "icon": "🌿",
    "verticals": [
      "ECO",
      "DESIGN",
      "FOOD",
      "FASHION"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.77,
      "tiers": 4,
      "lead_months": 111,
      "lead_tier": "science",
      "dom_vertical": "ECO",
      "dom_share": 0.38
    }
  },
  {
    "key": "inclusive_and_human_centric_design",
    "name_en": "Inclusive & Human-Centric Design",
    "description_en": "Universal accessibility, assistive technology, gender-inclusive products, aging-population design, neurodiversity accommodation, equity in design, modular/adaptive architecture, flexible workspaces.",
    "icon": "♿",
    "verticals": [
      "DESIGN",
      "LIFESTYLE",
      "HEALTH",
      "TECH",
      "FASHION"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.84,
      "tiers": 4,
      "lead_months": 140,
      "lead_tier": "science",
      "dom_vertical": "LIFESTYLE",
      "dom_share": 0.36
    }
  },
  {
    "key": "future_of_food_and_agriculture",
    "name_en": "Future of Food & Agriculture",
    "description_en": "Alternative proteins, precision agriculture, vertical farming, functional/fortified foods, food-as-medicine, novel ingredients.",
    "icon": "🌾",
    "verticals": [
      "FOOD",
      "TECH",
      "HEALTH",
      "ECO"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.65,
      "tiers": 4,
      "lead_months": 159,
      "lead_tier": "science",
      "dom_vertical": "FOOD",
      "dom_share": 0.51
    }
  },
  {
    "key": "connected_living_and_smart_spaces",
    "name_en": "Connected Living & Smart Spaces",
    "description_en": "IoT ecosystems, smart homes/kitchens/offices, ambient computing, sensor-driven environments, home automation, smart city infrastructure, transit-oriented development, urban public space activation.",
    "icon": "🏠",
    "verticals": [
      "TECH",
      "DESIGN",
      "FOOD",
      "BIZ",
      "ECO",
      "LIFESTYLE"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.74,
      "tiers": 4,
      "lead_months": 0,
      "lead_tier": "science",
      "dom_vertical": "TECH",
      "dom_share": 0.47
    }
  },
  {
    "key": "creator_economy_and_platform_shift",
    "name_en": "Creator Economy & Platform Shift",
    "description_en": "Content monetization, creator tools, decentralized media, platform economy, user-generated commerce, digital-native brands.",
    "icon": "📱",
    "verticals": [
      "LIFESTYLE",
      "TECH",
      "BIZ",
      "FASHION"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.6,
      "tiers": 2,
      "lead_months": -71,
      "lead_tier": "science",
      "dom_vertical": "LIFESTYLE",
      "dom_share": 0.46
    }
  },
  {
    "key": "platformization_of_culture",
    "name_en": "Platformization of Culture",
    "description_en": "Digital platforms become the central intermediaries controlling how creative content is produced, distributed, monetized and experienced across the entertainment industries — the structural counterpart to the creator economy (which is about the creators, not the gatekeepers).",
    "icon": "🎭",
    "verticals": [
      "LIFESTYLE",
      "BIZ",
      "TECH"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.47,
      "tiers": 1,
      "lead_months": null,
      "lead_tier": null,
      "dom_vertical": "BIZ",
      "dom_share": 0.69
    }
  },
  {
    "key": "bio_revolution_and_new_materials",
    "name_en": "Bio-Revolution & New Materials",
    "description_en": "Biotech-derived materials, synthetic biology, mycelium/algae/cellulose-based products, lab-grown alternatives, biomimicry.",
    "icon": "🧫",
    "verticals": [
      "ECO",
      "DESIGN",
      "FASHION",
      "FOOD",
      "HEALTH"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.44,
      "tiers": 4,
      "lead_months": 160,
      "lead_tier": "science",
      "dom_vertical": "TECH",
      "dom_share": 0.74
    }
  },
  {
    "key": "circular_economy_and_zero_waste",
    "name_en": "Circular Economy & Zero Waste",
    "description_en": "Closed-loop production systems, waste elimination, recyclability-by-design, reversible architecture, product-as-service models.",
    "icon": "♻️",
    "verticals": [
      "ECO",
      "DESIGN",
      "FASHION",
      "FOOD",
      "BIZ"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.66,
      "tiers": 4,
      "lead_months": 33,
      "lead_tier": "patent",
      "dom_vertical": "ECO",
      "dom_share": 0.54
    }
  },
  {
    "key": "climate_resilience_and_adaptation",
    "name_en": "Climate Resilience & Adaptation",
    "description_en": "Designing systems, buildings, and communities for climate change impact — flood-resistant architecture, heat adaptation, climate-smart agriculture.",
    "icon": "🌍",
    "verticals": [
      "ECO",
      "DESIGN",
      "FOOD",
      "LIFESTYLE"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.59,
      "tiers": 4,
      "lead_months": 36,
      "lead_tier": "science",
      "dom_vertical": "ECO",
      "dom_share": 0.65
    }
  },
  {
    "key": "experience_economy_and_immersive_design",
    "name_en": "Experience Economy & Immersive Design",
    "description_en": "Physical spaces as experience platforms — immersive retail, experiential dining, sensory environments, projection mapping, pop-up culture.",
    "icon": "✨",
    "verticals": [
      "DESIGN",
      "BIZ",
      "LIFESTYLE",
      "FOOD"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.69,
      "tiers": 4,
      "lead_months": 118,
      "lead_tier": "science",
      "dom_vertical": "LIFESTYLE",
      "dom_share": 0.53
    }
  },
  {
    "key": "cultural_heritage_and_identity",
    "name_en": "Cultural Heritage & Identity Renaissance",
    "description_en": "Revival of craft traditions, cultural fusion in design, place-based branding, indigenous knowledge integration, regional identity as differentiator.",
    "icon": "🏛️",
    "verticals": [
      "DESIGN",
      "FASHION",
      "LIFESTYLE",
      "FOOD"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.74,
      "tiers": 3,
      "lead_months": -5,
      "lead_tier": "science",
      "dom_vertical": "LIFESTYLE",
      "dom_share": 0.41
    }
  },
  {
    "key": "digital_trust_and_data_sovereignty",
    "name_en": "Digital Trust & Data Sovereignty",
    "description_en": "Data privacy, digital identity management, AI governance, algorithmic transparency, cybersecurity, content authentication.",
    "icon": "🔒",
    "verticals": [
      "TECH",
      "BIZ",
      "LIFESTYLE",
      "HEALTH"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.65,
      "tiers": 4,
      "lead_months": 71,
      "lead_tier": "science",
      "dom_vertical": "BIZ",
      "dom_share": 0.42
    }
  },
  {
    "key": "mental_health_and_neuro_wellness",
    "name_en": "Mental Health & Neuro-Wellness",
    "description_en": "Mental health technology, neuroscience-based consumer products, stress management tech, mindfulness platforms, biofeedback devices.",
    "icon": "🧠",
    "verticals": [
      "HEALTH",
      "TECH",
      "FASHION",
      "LIFESTYLE"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.56,
      "tiers": 4,
      "lead_months": 117,
      "lead_tier": "science",
      "dom_vertical": "HEALTH",
      "dom_share": 0.64
    }
  },
  {
    "key": "wearable_technology_and_augmented_living",
    "name_en": "Wearable Technology & Augmented Living",
    "description_en": "Smart wearables, health monitoring devices, AR/VR integration, smart textiles, brain-computer interfaces, augmented senses.",
    "icon": "⌚",
    "verticals": [
      "TECH",
      "HEALTH",
      "FASHION",
      "DESIGN"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.56,
      "tiers": 4,
      "lead_months": -42,
      "lead_tier": "patent",
      "dom_vertical": "TECH",
      "dom_share": 0.59
    }
  },
  {
    "key": "virtual_worlds_consolidation",
    "name_en": "Virtual Worlds Consolidation & Post-Metaverse Reckoning",
    "description_en": "Retreat and consolidation of social VR, metaverse platforms and social gaming spaces after the hype cycle — platform closures, nostalgia-driven revivals of early digital communities, shift from immersive virtual worlds back to lighter social formats, rethinking of what persistent virtual spaces should be.",
    "icon": "🕶️",
    "verticals": [
      "LIFESTYLE",
      "TECH",
      "BIZ"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.64,
      "tiers": 2,
      "lead_months": -12,
      "lead_tier": "science",
      "dom_vertical": "TECH",
      "dom_share": 0.46
    }
  },
  {
    "key": "geopolitical_disruption_and_supply_chain_resilience",
    "name_en": "Geopolitical Disruption & Supply Chain Resilience",
    "description_en": "Tariff impacts, trade wars, energy security concerns, supply chain diversification, reshoring, geopolitical risk pricing, sanctions effects.",
    "icon": "🌐",
    "verticals": [
      "BIZ",
      "ECO",
      "LIFESTYLE",
      "TECH"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.59,
      "tiers": 4,
      "lead_months": 108,
      "lead_tier": "science",
      "dom_vertical": "BIZ",
      "dom_share": 0.53
    }
  },
  {
    "key": "quantum_information_science",
    "name_en": "Quantum Information Science",
    "description_en": "Manipulating and processing information at atomic and subatomic scales — quantum computing hardware, error correction, quantum networking and sensing, and the surrounding materials and control-systems research moving toward fault tolerance.",
    "icon": "⚛️",
    "verticals": [
      "TECH",
      "BIZ"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.4,
      "tiers": 4,
      "lead_months": 9,
      "lead_tier": "funding",
      "dom_vertical": "TECH",
      "dom_share": 0.76
    }
  },
  {
    "key": "next_generation_semiconductors",
    "name_en": "Next-Generation Semiconductor Architectures",
    "description_en": "The evolution of chip design and manufacturing beyond classical scaling — advanced packaging, specialized accelerators, neuromorphic and photonic approaches, and the geopolitically charged buildout of fabrication capacity.",
    "icon": "💾",
    "verticals": [
      "TECH",
      "BIZ",
      "ECO"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.39,
      "tiers": 4,
      "lead_months": 139,
      "lead_tier": "science",
      "dom_vertical": "TECH",
      "dom_share": 0.79
    }
  },
  {
    "key": "orbital_economy_expansion",
    "name_en": "Orbital Economy Expansion",
    "description_en": "Commercialization and industrialization of Earth orbit and beyond — scalable launch systems, satellite constellations and services, in-orbit manufacturing and logistics, and the supporting robotics and ground infrastructure.",
    "icon": "🚀",
    "verticals": [
      "TECH",
      "BIZ",
      "ECO"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.49,
      "tiers": 2,
      "lead_months": -40,
      "lead_tier": "science",
      "dom_vertical": "TECH",
      "dom_share": 0.67
    }
  },
  {
    "key": "evolution_of_work_models",
    "name_en": "Evolution of Work Models",
    "description_en": "Structural transformation of how, where and under what conditions work is organized and compensated — remote and hybrid work, workplace culture and monitoring, labor rights, skills shifts and the renegotiation of the employer-employee contract.",
    "icon": "💼",
    "verticals": [
      "BIZ",
      "LIFESTYLE",
      "TECH"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.62,
      "tiers": 2,
      "lead_months": -95,
      "lead_tier": "science",
      "dom_vertical": "BIZ",
      "dom_share": 0.46
    }
  },
  {
    "key": "education_and_lifelong_learning",
    "name_en": "Education & Lifelong Learning",
    "description_en": "Continuous transformation of educational pathways — EdTech and digital delivery, STEM pipelines and student retention, workforce reskilling, equity of access, and the shift from front-loaded degrees to lifelong skill formation.",
    "icon": "🎓",
    "verticals": [
      "LIFESTYLE",
      "TECH",
      "BIZ"
    ],
    "megatrend": false,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.77,
      "tiers": 3,
      "lead_months": 147,
      "lead_tier": "science",
      "dom_vertical": "LIFESTYLE",
      "dom_share": 0.37
    }
  },
  {
    "key": "digital_healthcare_integration",
    "name_en": "Digital Healthcare Integration",
    "description_en": "Digital health technologies maturing from pilots into standardized, reimbursed components of clinical care — telehealth, remote monitoring, provider IT, healthcare access platforms and the operational integration of health data.",
    "icon": "🩺",
    "verticals": [
      "HEALTH",
      "TECH",
      "BIZ"
    ],
    "megatrend": true,
    "measured": {
      "measured_at": "2026-08-08",
      "reach": 0.62,
      "tiers": 4,
      "lead_months": 107,
      "lead_tier": "science",
      "dom_vertical": "HEALTH",
      "dom_share": 0.59
    }
  }
];
